services:
  proto:
    image: docker.io/pavelguskov/proto_serialization
    environment:
      - PORT=9000
    expose:
      - 9000
  json:
    image: docker.io/pavelguskov/json_serialization
    environment:
      - PORT=9000
    expose:
      - 9000
  xml:
    image: docker.io/pavelguskov/xml_serialization
    environment:
      - PORT=9000
    expose:
      - 9000
  pickle:
    image: docker.io/pavelguskov/pickle_serialization
    environment:
      - PORT=9000
    expose:
      - 9000
  avro:
    image: docker.io/pavelguskov/avro_serialization
    environment:
      - PORT=9000
    expose:
      - 9000
  yaml:
    image: docker.io/pavelguskov/yaml_serialization
    environment:
      - PORT=9000
    expose:
      - 9000
  msgpack:
    image: docker.io/pavelguskov/msgpack_serialization
    environment:
      - PORT=9000
    expose:
      - 9000
  proxy:
    image: docker.io/pavelguskov/proxy_serialization
    env_file:
      - ./proxy.env
    ports:
      - "2000:2000"
