# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: user.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Friend(betterproto.Message):
    id: int = betterproto.int64_field(1)
    money: float = betterproto.double_field(2)
    name: str = betterproto.string_field(3)


@dataclass
class User(betterproto.Message):
    name: str = betterproto.string_field(1)
    id: int = betterproto.int64_field(2)
    friends: List["Friend"] = betterproto.message_field(3)
    cars: List[str] = betterproto.string_field(4)


@dataclass
class TestingData(betterproto.Message):
    users: List["User"] = betterproto.message_field(1)
